### PR TITLE
CA-234525: Don't initialise SR for VDI operations

### PR DESCRIPTION
**Pull request by chandrikas**
Signed-off-by: Chandrika Srinivasan <chandrika.srinivasan@citrix.com>

### CODE REVIEW

**Comment by MarkSymsCtx** [comment]
This change will require further work to address a regression. Do not merge as is.

**Comment by germanop** [comment]
What is the status of this PR?
There is a version we have been testing in the last 2 months what is missing?

**Comment by MarkSymsCtx** [comment]
The version in testing is an entirely different approach to achieve the same aim. This PR should probably be closed and a new one opened.

**Comment by germanop** [comment]
I am gonna push the updated version

**Comment by MarkSymsCtx** [comment]
Yes, please 😊

**Pull request closed without merging**
