### PR TITLE
CA-356411: correct check for session

### PR DESCRIPTION
**Pull request by MarkSymsCtx**

### CODE REVIEW

**Review by rosslagerwall — DISMISSED** [review]

**Review by edwintorok — APPROVED** [review]
I hope this won't reintroduce the problems we had when plugging 100s of SRs on boot. I recommend running the 'manysrs' testcase after this is built.

**Comment by MarkSymsCtx** [comment]
> I hope this won't reintroduce the problems we had when plugging 100s of SRs on boot. I recommend running the 'manysrs' testcase after this is built.

Running now.

**Comment by edwintorok** [comment]
Determined that `not s` invokes `__nonzero__` API call in XAPI (the xmlrpc proxy forwards everything, including special method calls), whereas `s is None` doesn't invoke any builtin methods.

**Comment by stormi** [comment]
> Determined that `not s` invokes `__nonzero__` API call in XAPI (the xmlrpc proxy forwards everything, including special method calls), whereas `s is None` doesn't invoke any builtin methods.

Maybe this subtlety would deserve a comment in the code, or at least a mention in the commit message?

**Comment by stormi** [comment]
(By the way as an external observer it's really hard to understand the reasons for any changes when all we have in the commit messages is a Citrix internal CA number)

**Comment by MarkSymsCtx** [comment]
> > Determined that `not s` invokes `__nonzero__` API call in XAPI (the xmlrpc proxy forwards everything, including special method calls), whereas `s is None` doesn't invoke any builtin methods.
> 
> Maybe this subtlety would deserve a comment in the code, or at least a mention in the commit message?

It should but it actually belongs on the Xapi Python API docs.

**Review by rosslagerwall — APPROVED** [review]

**Review by TimSmithCtx — APPROVED** [review]

**Review by edwintorok — APPROVED** [review]

**Pull request merged**
