### PR TITLE
CP-11979: Added FCoE driver and fixed sr-probe.

### PR DESCRIPTION
**Pull request by pritha-srivastava**
Signed-off-by: Pritha Srivastava <pritha.srivastava@citrix.com>

### CODE REVIEW

**Comment by chandrikas** [comment]
@pritha-srivastava is this PR complete? I don't see changes to Makefile etc to include this driver in the RPM.

**Comment by pritha-srivastava** [comment]
I think the Makefile has been missed. I'll re-submit the PR.

**Comment by chandrikas** [comment]
@pritha-srivastava , could we please refresh this PR?

**Comment by pritha-srivastava** [comment]
@chandrikas : I've added the Makefiles to the pull request. This is the first one in the series of patches for FCoE (which has been already reviewed by you earlier). I'll create pull requests for ones that are dependant on this once this reviewed. Let me know if I need to do something else

**Pull request closed without merging**
