### PR TITLE
CP-15900: Handle new Tools ISO name

### PR DESCRIPTION
**Pull request by robhoes**

### CODE REVIEW

**Comment by robhoes** [comment]
This is a followup to #297. This PR includes the patch from the other PR, because the latter was not yet merged and the new patch depends on it.

**Comment by chandrikas** [comment]
New changes have been added to patchqueue

**Comment by germanop** [comment]
@robhoes do they need to be 2 commits?

**Comment by robhoes** [comment]
@germanop Nope, it just ended up this way because minds were changed along the way. Shall I squash the patches in the PR and close the other?

**Comment by germanop** [comment]
Close all the PR that are not needed. For squashing, it is not a problem. If it needs to be one commit only, just tell me which commit message has to be kept otherwise I can push both commits.
But, yes, if you want to rearrange the commits in this PR, it is more than welcome.

I will compare it again with what we have in our patch queue to check there are no differences in code.

**Comment by robhoes** [comment]
@germanop I've now combined the two patches into one, and have closed #297.

**Comment by germanop** [comment]
Thank you. I will close this as soon as we can.

**Pull request closed without merging**
