### PR TITLE
NFS4.1 Support

### PR DESCRIPTION
**Pull request by MrMEEE**

### CODE REVIEW

**Comment by MrMEEE** [comment]
Hi

I'm not really good with git (something that is on my todo-list).. 

I have done the rebase and amend.. now when I try to push I get a:
```
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>
```
What do I do from here???

**Comment by MarkSymsCtx** [comment]
It looks like you haven't completed the rebase, `git rebase --continue` may help here.

A useful reference is https://git-scm.com/book/en/v2

**Comment by MarkSymsCtx** [comment]
Martin, I've combined all these changes and checked the signoff. Please take a look and confirm that you're happy with the changeset now.

**Comment by MrMEEE** [comment]
Looks perfekt..

**Comment by MrMEEE** [comment]
Cool :)

**Comment by MarkSymsCtx** [comment]
Thank you.

**Pull request merged**
