### PR TITLE
Added Multipath Config for DELL ME4 iSCSI-NAS

### PR DESCRIPTION
**Pull request by vafgoettlich**

### CODE REVIEW

**Comment by MarkSymsCtx** [comment]
This PR is in no way fit for merging, try again.

**Comment by vafgoettlich** [comment]
Can you give me a hint what I have to change?

**Comment by stormi** [comment]
You rebase broke your branch so it will be easier to start over from scratch.

**Comment by stormi** [comment]
A few tips:
* Your current branch diverged a lot from the master branch. We expect just one commit and see 22 of them.
* As the change you want to contribute is small and you don't know git well, I suggest the following:
  * Fork the upstream `sm` repository from https://github.com/xapi-project/sm
  * Clone your forked repo into a new directory.
  * Checkout the master branch `git checkout master`
  * Create a new branch for your fix `git checkout -b fix-qnap-multipath`
  * Change multipath.conf, then `git add [...]`, `git commit -s` (`-s` automatically adds a sign-off to your commit message. Don't remove it). Push: `git push -u origin fix-qnap-multipath`
  * Go to your forked repo in github's interface and create a new PR from that branch

**Pull request closed without merging**
