### PR TITLE
Additional SM Driver for MooseFS

### PR DESCRIPTION
**Pull request by xandrus**
Hi,

I would like to add an additional SM driver for MooseFS distributed file system.

Thanks!

### CODE REVIEW

**Comment by edwintorok** [comment]
Thanks, I think we'd prefer new storage drivers to use SMAPIv3 instead of SMAPIv1 though.
See https://xapi-project.github.io/xapi-storage/#introduction https://github.com/xapi-project/xapi-storage/tree/master/python/examples

SMAPIv1 is difficult to maintain, and has some architectural issues that were corrected in SMAPIv3. Also SMAPIv3 should have better documentation on the semantics of each API call that a storage driver has to implement.

**Comment by MarkSymsCtx** [comment]
Thanks for this, unfortunately we are no longer accepting new SRs
using v1 of the SM API, it is deprecated in preference to the v3
(SMAPIv3) API. See here -
https://xapi-project.github.io/xapi-storage/#introduction with simple
example implementations here -
https://github.com/xapi-project/xapi-storage/tree/master/python/examples.

The new API enforces a cleaner separation between the control plane
and the implementation of the storage management which improves
reliability and facilitates independent testing of the SR
implementation without any specific control plane implementation.

**Comment by olivierlambert** [comment]
I understand the answer, but SMAPIv3 doesn't have:

* any migration mechanism from SMAPIv1
* no VHD nor QCOW2 export format (hard to backup, and NBD implem in XAPI is incomplete)
* still perf issues
* a complete lack of example integration outside a non-documented proprietary Citrix driver

So I agree new drivers should transition to SMAPIv3, but it's not production ready yet for the community to participate. My 2 cents.

**Comment by xandrus** [comment]
Thank you for all the information.

Thanks!

**Comment by MarkSymsCtx** [comment]
SMAPIv3 also allows you to use the full power of the storage rather than being tied to a lowest common denominator of VHD that SMAPIv1 forces on you.

In the case here of MooseFS you don't need, and therefore probably shouldn't use, and form of image format and can use files on the filesystem as direct raw virtual disk files. Snapshot and Cloning can be performed using `mfsmakesnapshot` to perform a server side offloaded snasphot operation. No requirement for any SR level garbage collection and no indirection via a performance bottlenecking image format process.

**Comment by olivierlambert** [comment]
Yes, that's a great thing (and also SMAPIv3 code is far better shape).

However, how would you backup this at the hypervisor level? Exporting the raw content directly?

**Pull request closed without merging**
