### PR TITLE
CA-161436: Disable caching for CIFS ISO SRs

### PR DESCRIPTION
**Pull request by siddharthv**
This patch does a bit of refactoring to set the mount options correctly for
CIFS ISO SRs. This patch sets `cache=none`.

Signed-off-by: Siddharth Vinothkumar <siddharth.vinothkumar@citrix.com>

### CODE REVIEW

**Comment by franciozzy** [comment]
Reviewed-by: Felipe Franciosi <felipe@paradoxo.org>

**Comment by germanop** [comment]
This PR is under testing in our internal patch queue

**Comment by germanop** [comment]
@franciozzy , post here your improvements

**Comment by franciozzy** [comment]
This PR replaced the previous occurrences of code that added CIFS credentials with a more generic code that adds CIFS mount options. One of those occurrences were (already) incorrectly placed (they were previously returning None, so no problem was spotted). After CA-161436's changes, we started to add "cache=none" on mount commands for shares other than CIFS (e.g. NFS).

I've patched that in our PQ and the resulting code passed the BST (which was failing after this PR). @siddharthv : Can you amend the PR, please?

**Comment by siddharthv** [comment]
@franciozzy I've amended this PR as requested. Please have a look when you have the time.

**Comment by franciozzy** [comment]
@siddharthv looks good now!

**Pull request closed without merging**
