### PR TITLE
CA-369613: report errors correctly from multipath

### PR DESCRIPTION
**Pull request by MarkSymsCtx**
Signed-off-by: Mark Syms <mark.syms@citrix.com>

### CODE REVIEW

**Review by TimSmithCtx — APPROVED** [review]

**Review by edwintorok — APPROVED** [review]
These look OK. Are there any XenCenter updates needed as a result of this, or will the SDK automatically pick this up on next build?

**Comment by edwintorok** [comment]
@kc284 FYI

**Comment by MarkSymsCtx** [comment]
> These look OK. Are there any XenCenter updates needed as a result of this, or will the SDK automatically pick this up on next build?

Good point, yes we'll should add these as localised message although they should only occur in rare error cases, i.e. if entirely bogus input data is provided, it just happened that XenRT did that as a result of commissioning a new SAN.

**Comment by kc284** [comment]
> These look OK. Are there any XenCenter updates needed as a result of this, or will the SDK automatically pick this up on next build?

It will pick them automatically (see first line of sdk recipe in xapi's Makefile).

**Pull request merged**
