### PR TITLE
Remove obsolete unused pip confiuration

### PR DESCRIPTION
**Pull request by MarkSymsCtx**

### CODE REVIEW

**Review by rosslagerwall — APPROVED** [review]

**Comment by edwintorok** [comment]
This is now failing due to the newer version of pylint complaining.

**Comment by MarkSymsCtx** [comment]
> This is now failing due to the newer version of pylint complaining.

Yes, and as Github has a different version of pylint3 to what we have it can't be striaghtforwardly fixed without repeated pushes to github :(

**Comment by ydirson** [comment]
> Yes, and as Github has a different version of pylint3 to what we have it can't be striaghtforwardly fixed without repeated pushes to github :(

I can reproduce quite easily those errors by installing in a venv.

**Comment by ydirson** [comment]
If that's OK with you @MarkSymsCtx I'll deal with the pylint errors to unblock this PR

**Pull request closed without merging**
