### PR TITLE
CA-212295: Stale Refcount files on pool slaves after coalescing

### PR DESCRIPTION
**Pull request by kostaslamda**
Force unlink a VHD's refcount in cleanup.LVHDSR.deleteVDI()
on all pool slaves.

Signed-off-by: Kostas Ladopoulos <Konstantinos.Ladopoulos@citrix.com>

### CODE REVIEW

**Comment by stefanopanella** [comment]
It looks fine to me

**Comment by stefanopanella** [comment]
I had a look at the last changes for leaf-coalesce as well and they look good.

**Comment by germanop** [comment]
@stefanopanella , would you please ack the latest change to this pull request?
Your last comment is before that change

**Comment by germanop** [comment]
@kostaslamda , squash the commits and make sure the remaining one have an appropriate commit message

**Pull request closed without merging**
